### ISSUE TITLE
Maintenance work and updates

### ISSUE THREAD

**Issue by feldi-online** [citeac/citeproc-node#1]
The last commit in this project was already a long time ago. Is there still anyone who maintains this repository?

Several dependencies, especially csl-styles and csl-locales received lots of updates and bug fixes which are not included here so far. Since there are several important fixes, an update is unavoidable. Does anyone here feel responsible for this?

I am also happy to provide a PR to update the dependencies, just let me know!

**Comment by nickjackson** [comment]
If I remember correctly, this repo is a fork of https://github.com/zotero/citeproc-node. It looks like that repo is better maintained. 

We no longer use this fork, its just public for prosperity sake.
